---
- name: Elimina repos enterprise
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent 

- name: Agrega repos community
  apt_repository:
    repo: deb "{{ repo }}" buster pve-no-subscription
    state: present

- name: Actualiza la cache de los repos
  apt:
    update_cache: yes

- name: Instalacion de python-apt 
  apt:
    name: python-apt
    state: present    

- name: Instalación de pip 
  apt:
    name: ['python-pip', 'python-dev', 'build-essential']
      
- name: Actualizacion de pip
  pip:
    name: pip
    state: latest

- name: Instalacion de dependencias ansible
  pip:
    name: ['requests', 'proxmoxer']
    